### ISSUE TITLE
Fix colour fading effect

### ISSUE THREAD

**Issue by andkamau** [CfKenya-KMP/OurTime2Eat#7]
<img width="1245" alt="screen shot 2016-07-26 at 21 42 48" src="https://cloud.githubusercontent.com/assets/647123/17150920/fbb3ff82-5379-11e6-830a-239f5229fda5.png">

There's a row that fades to white

**Comment by huston-skyline** [comment]
@andkamau are you sure you're not showing more than 9 elements in that section?

**Comment by andkamau** [comment]
beca58c028c1b619bc45ba5b9cf21733866c52e0
